### ISSUE TITLE
Research Flutter and Dart

### ISSUE THREAD

**Issue by SpencerIsTheKey** [SpencerIsTheKey/OmmatyB#2]
The client wants to use Flutter and Dart as the front-end technology. None of the team are familiar, so this needs to be research so that we can follow the client's expectation.

**Comment by zil93** [comment]
For Tech stack provide at least 3 solutions with pros and cons for each 
Consider mentioning features for each milestone
Prepare requirement document (Functional and non-functional)
Decide on Test strategy

**Comment by SpencerIsTheKey** [comment]
Everyone on the team has become familiar with what Flutter and Dart can do. The team members who have decided to work as our primary front-end developers will now be responsible for #5
